### ISSUE TITLE
Could not connect to registration page

### ISSUE THREAD

**Issue by j3kstrum** [TheNergaL/foodapp#74]
Hi,

I had a strange bug while beta testing that suddenly I can't reproduce. I signed on to the site and tried to register, but clicking the "don't have an account, register here" button kept redirecting me to the page I was already on. After a few clicks, however, I waited a few seconds and now the button works every time.

I don't think there's much you can do about this unless you can reproduce it yourselves. It's also very trivial, but I wanted to make sure you guys knew about it.

Best of luck with the remainder of your semesters!

**Comment by tuckerpo** [comment]
Thanks for the heads-up. This is something we're gonna look into.
