### ISSUE TITLE
Security bug

### ISSUE THREAD

**Issue by QinxinTian** [TheNergaL/foodapp#81]
<img width="1199" alt="2017-11-04 3 48 23" src="https://user-images.githubusercontent.com/25886116/32403546-38fe9bba-c113-11e7-92c6-4195974dc954.png">
I found a bug here.

**Comment by doyom123** [comment]
What is the bug? Write some details.

**Comment by QinxinTian** [comment]
See the place above the "password."

**Comment by doyom123** [comment]
Yes, what exactly is the security vulnerability here?
