### ISSUE TITLE
I can't log in after registration

### ISSUE THREAD

**Issue by QinxinTian** [TheNergaL/foodapp#82]
[Screen Capture 0.flv.zip](https://github.com/TheNergaL/foodapp/files/1443090/Screen.Capture.0.flv.zip)

**Comment by mittal-aman** [comment]
#82 
I think you will be able to login with your username you used to register and not your email id.We used the username to check in our database and not the email id.Please try again and let us know if the problem is still there. Thanks and sorry for the confusion .
