### ISSUE TITLE
The email and username can be registered for twice.

### ISSUE THREAD

**Issue by QinxinTian** [TheNergaL/foodapp#87]
[Screen Capture 10.mov.zip](https://github.com/TheNergaL/foodapp/files/1443783/Screen.Capture.10.mov.zip)
In our common sense, the same email address can't be registered for twice even with the same username, but it does not give me the error.

**Comment by QinxinTian** [comment]
You just marked TWO MAJOR issue #85 and #86 as duplicates, they are not duplicates. You only left the least major bug open. The issue 85 is "Database isn't implemented well, the same email address can be registered for twice with different user name and both username can then be used for logging in". The issue #86 is "If I sign up twice for one same username but 2 different email address, it should have given me the error." They are not duplicates.

**Comment by tuckerpo** [comment]
They were marked as duplicates because both issues were solved with the same change in the codebase.
