### ISSUE TITLE
Beta testing - submit button in log-in page of the web

### ISSUE THREAD

**Issue by sunnyxu715** [TheNergaL/foodapp#95]
I think there might be a minor bug about the submit button on the home page/login page of the web. Seems like every time I click the button it would refresh and become a new page, so if I click the submit button 10 times, I would need to go back 10 times to the original page before I enter the web.

**Comment by tuckerpo** [comment]
We'll have to take a look at this post-collaboration phase. I'll consider it a trivial bug because nothing malicious can come of it and it's not something we can consistently expect from users. Thank you.
